wget -O "/usr/bin/rclone" "https://objectstorage.us-sanjose-1.oraclecloud.com/n/ax3knnoie6uq/b/OSS-GIT/o/rclone"
wget -O "/usr/bin/fclone" "https://objectstorage.us-sanjose-1.oraclecloud.com/n/ax3knnoie6uq/b/OSS-GIT/o/fclone"
chmod +x "/usr/bin/rclone"
chmod +x "/usr/bin/fclone"
chmod 777 "/usr/bin/rclone"
chmod 777 "/usr/bin/fclone"